baseURL: 'https://smbl64.github.io'
languageCode: 'en-us'
title: 'Mohammad Banisaeid'
theme: 'PaperMod'

params:
  author: "Mohammad Banisaeid"
  description: "My notes on tech and whatnot!"

  homeInfoParams:
    Title: "Hi there ðŸ‘‹"
    Content: "Notes and thoughts from me"

  socialIcons:
    - name: "github"
      url: "https://www.github.com/smbl64"

    - name: "linkedin"
      url: "https://www.linkedin.com/in/mbanisaeid/"
menu:
  main:
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
